version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  publisher_redis:
    build:
      context: ./publisher_redis
    ports:
      - '8000:8000'
    depends_on:
      - redis
  listener_redis:
    build:
      context: ./listener_redis
    ports:
      - '8001:8000'
    depends_on:
      - redis
